server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: SmartStockPicture
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.55.253.41 :3306/CloudPicture?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: qq2134769644
    # MyBatis-Plus配置
